services:
  db-server:
    build: ./mysql/ # use mysql folder
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  app:
    build: ./python/ # use python folder
    command: sh -c 'sleep 5s ; python3 ./insert_values.py; python3 ./main.py'
    depends_on:
    - db-server


    # volumes: # run the sql script (optinal cause I already have a run script in Dockerfile)
    #   - ./mysql:/docker-entrypoint-initdb.d